# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings

title: PET Física - UFRPE
email: petfisica.ufrpe@gmail.com
description: "Programa de Educação Tutorial da licenciatura em Física da Universidade Federal Rural de Pernambuco, (PET Física - UFRPE)."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://petfisicaufrpe.github.io" # the base hostname & protocol for your site
github_username:  petfisicaufrpe
facebook_username: petfisicaufrpe

# Build settings    
markdown: kramdown
# permalink: /:categories/:year/:month/:day/:title
# permalink: /:year/:month/:day/:title
permalink: /:title